### PR TITLE
core: subtract deposit gas from pool, so other txs do not use the same gas

### PR DESCRIPTION
**Pull request by protolambda**
Previously deposits would correctly reflect their gas usage in the `ExecutionResult` which would then be reflected in the `header.GasUsed`, but the gas-pool (initially filled with gas limit) would not be drained from the deposit gas, causing other transactions (if you spam enough in a test) to use the same gas from the pool, and thus creating a block with `GasUsed >= GasLimit`.

This updates the `preCheck` deposit code-path to do the gas-pool update part of the `buyGas` which we otherwise skip (deposits are paid for on L1, not L2).
Additionally I cleaned up the unnecessarily nested `if` in the `TransitionDb` and added a statement to make sure that if deposits ever go over the gas-limit, the deposit is not included as failing deposit, but block-production fails. (L2 gas limit should never be reached, the L1 deposit contract tracks total deposit gas + plus we have a margin for system deposits which will soon be excepted as 0 gas consumption).

Note: this fix is based on a bug report, but it is a speculative fix until I'm able to test the difference with the previous code.

Credit to @lucasgleba + Lattice team for finding this issue and providing a detailed bug report :clap: 

Fixes ENG-2530

### CODE REVIEW

**Comment by trianglesphere** [comment]
> statement to make sure that if deposits ever go over the gas-limit, the deposit is not included as failing deposit, but block-production fails.

This does return `ErrGasLimitReached`, but I think that actually is skipped during block production (but does correctly stall block verification). I think we need to halt on block production otherwise we drop deposits.

**Comment by protolambda** [comment]
@trianglesphere right, when deposits can't be included at all I think we may want to halt the chain (i.e. not build a block) instead of silently dropping them. E.g. currently an internal out of gas error is transformed into evm fail, but `ErrGasLimitReached` is special since it breaks a hard invariant, and should thus not be processed like the out-of-gas deposiut (since we can't produce a block with valid gas usage). Shall I update the miner code to stop building on such invariant that breaks?

**Comment by trianglesphere** [comment]
> Shall I update the miner code to stop building on such invariant that breaks?

Yep, I think that makes the most sense here.

**Comment by protolambda** [comment]
Will open a new PR for miner code update.

cherry-picked onto `optimism-history` branch, will rebase that branch on latest upstream, and then update `optimism-prototype`

**Pull request closed without merging**
