### PR TITLE
Added entrypoint script for Dockerfile

### PR DESCRIPTION
**Pull request by optimisticben**
**Description**
Pull the entrypoint.sh script from the op-bedrock setup to this, upstream, docker image.

This is needed in order to use the same image for deployments.

### CODE REVIEW

**Review by mslipper — APPROVED** [review]

**Review by mslipper — CHANGES_REQUESTED** [review]
I think we should have a separate Dockerfile for this. That would let us build an internal image with our custom entrypoint while eliminating the diff between native Geth's Dockerfile.

We can set up a custom image builder in CircleCI pretty easily.

**Comment by optimisticben** [comment]
Updated to build another image with the script. Is this what you had in mind?

**Comment by protolambda** [comment]
I don't think we should change any devops things in this repo, but rather move it into a separate repo and start the job with webhooks (or whatever other trigger we can use). The extra configuration files, docker changes, CI changes etc. all add to the diff while they can just be hosted somewhere else. I do think they are important, but minimizing this repo to just a few compatible code changes helps a lot with the relation to L1.

**Comment by optimisticben** [comment]
k, I'll move it somewhere else!

**Pull request closed without merging**
